[package]
name = "jwt-check"
version = "0.1.0"
authors = ["tek-shinobi <tek.shinobi.ninja@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.13.0"
clap = "2.33"
serde = "1.0"
serde_json = "1.0"
